services:
    # api:
    #     image: node
    #     container_name: api
    #     working_dir: /app
    #     volumes:
    #         - .:/app
    #     ports:
    #         - 4100:4100
    #     command: bash -c "npm i -g pnpm json-server && pnpm install && npm run build && npm run json"

    web:
        image: nginx
        container_name: web
        volumes:
            - ./dist/hr-system/:/usr/share/nginx/html/
        ports:
            - 80:80
